env:
  browser: true
  commonjs: true
  node: true
  es6: true
  jquery: true
  mocha: true
extends: 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
