language: node_js
node_js: '8'
install:
  - npm install mocha -g
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
  - mysql -e 'CREATE USER blitz@localhost;'
  - mysql -e 'GRANT ALL PRIVILEGES ON *.* TO blitz@localhost;'
  - mysql -e 'ALTER USER blitz@localhost IDENTIFIED WITH mysql_native_password BY "";'
