language: node_js
node_js: '8'
install:
  - npm install mocha -g
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;CREATE USER 'blitz'@'localhost';
GRANT ALL privileges ON *.* TO 'blitz'@'localhost';
ALTER USER 'blitz'@'localhost' IDENTIFIED WITH mysql_native_password BY '';'
